# Reference documentation
# https://docs.gitlab.com/ee/ci/yaml/README.html


image: continuumio/miniconda3

before_script:
  - conda install --yes --file requirements.txt
  - conda install --yes --file requirements-test.txt
  - pip install .

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - pylint subsample_seq

test:
  stage: test
  script:
    - pytest tests
